apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bulkintel-hpa
  namespace: bulkintel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bulkintel
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
