apiVersion: v1
kind: Service
metadata:
  name: bulkintel
  namespace: bulkintel
spec:
  selector:
    app: bulkintel
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
  type: ClusterIP
