apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulkintel
  namespace: bulkintel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bulkintel
  template:
    metadata:
      labels:
        app: bulkintel
    spec:
      containers:
      - name: bulkintel
        image: localhost:32000/bulkintel:v1
        resources:
          requests:
            cpu: "100m" # Minimum CPU resources required
          limits:
            cpu: "500m" # Maximum CPU resources allowed
        command: ["/bin/sh","-c"]
        args: ["python manage.py migrate && gunicorn --workers 3 --bind 0.0.0.0:9005 bulkintel.wsgi:application"]
        volumeMounts:
        - name: sqlite-storage
          mountPath: /data
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bulkintelsecrets
              key: SECRET_KEY
        - name: ABUSEIPDB_KEY
          valueFrom:
            secretKeyRef:
              name: bulkintelsecrets
              key: ABUSEIPDB_KEY
        - name: VIRUSTOTAL_KEY
          valueFrom:
            secretKeyRef:
              name: bulkintelsecrets
              key: VIRUSTOTAL_KEY
        - name: BIG_DATA_USERAGENT_KEY
          valueFrom:
            secretKeyRef:
              name: bulkintelsecrets
              key: BIG_DATA_USERAGENT_KEY
        ports:
        - containerPort: 9005
      volumes:
      - name: sqlite-storage
        hostPath:
          path: /data
