apiVersion: v1
kind: Service
metadata:
  name: ipchecker
  namespace: ipchecker-pre-release
spec:
  selector:
    app: ipchecker
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
  type: ClusterIP
