apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa # Name of the autoscaling resource
  namespace: ipchecker-pre-release
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment # Type of resource
    name: nginx # Deployment name
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50 # In this case the autoscaling will try to maintain an average CPU utilization across all Pods of 50%
