apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: bulkintel
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32555  # Specify the NodePort or let Kubernetes assign one
  type: NodePort
